#
#  File:          Makefile
#
#  Author:        Daiki Sanno
#
#  Created:       November 25, 2006
#
#  Modified:      November 25, 2006
#

TARGET = reversi

SRCS = \
	main.c \
	board.c \
	com.c \
	evaluator.c \
	opening.c \

OBJS = $(SRCS:.c=.obj)

CC = bcc32
INC = 
DEFS = 
OPTS = 
CFLAGS = $(INC) $(DEF) $(OPTS)
LDFLAGS = 


$(TARGET) : $(OBJS)
	$(CC) -e$(TARGET) $(CFLAGS) $(OBJS) $(LDFLAGS)
.cpp.obj:
	$(CC) $(CFLAGS) -c $<

all : $(TARGET)
clean :
	del $(OBJS) $(TARGET).tds

